### ISSUE TITLE
Create Inspection Data Mart model (gold) in SQL DB

### ISSUE THREAD

**Issue by rkapai** [bcgov/Mines-Data-Platform#102]
Feature #5

**Comment by vrutstein** [comment]
The Inspection model has been designed in SQL DB
The model was created in Power BI

Working on Power BI Getway setuo
Power BI model

**Comment by vrutstein** [comment]
1st iteration of the ADF Pipelines development has been finished. The Inspection DM was populated/refreshed. The data is up to date.
Working on Power BI workspace connectivity and PBI Gateway setup.
