### ISSUE TITLE
app.powerbi.com DNS resolution and connectivity error

### ISSUE THREAD

**Issue by mahyargorji** [bcgov/Mines-Data-Platform#106]

**Comment by mahyargorji** [comment]
![Image](https://github.com/user-attachments/assets/8217a82c-2547-4090-86de-bd074c419c40)

**Comment by vrutstein** [comment]
Followed up the service request today. 

Thibault Breboin commented:
Good morning Vlad,
Thank you for your request. The team started looking into this on Friday, I will make sure you can get an update today.
Thank you,
Thibault
