### ISSUE TITLE
Assess and identify the tools supporting the data architecture

### ISSUE THREAD

**Issue by rkapai** [bcgov/Mines-Data-Platform#18]
Feature: #5 

Description: 

Acceptance Criteria:

Other Considerations:

**Comment by vrutstein** [comment]
https://bcgov-my.sharepoint.com/:f:/g/personal/vlad_rutstein_gov_bc_ca/Eul25m6iCDBCpB8t_6LoEl0Bkof0FjPACE-7C0Id2lqwjw?email=Vlad.Rutstein%40gov.bc.ca&e=rkNPNW

**Comment by vrutstein** [comment]
see the tools in the diagrams above
