### ISSUE TITLE
Export current ETL pipelines to IaC

### ISSUE THREAD

**Issue by rkapai** [bcgov/Mines-Data-Platform#182]
Export current ETL pipelines, sources and sinks to git repo for best practices.

**Comment by mahyargorji** [comment]
Update: 
Spoke with Vlad, did some investigation together in Data Factory capabilities and gaps in OCIO LZ
Exporting to GIT would require BCGOV git organization owner approval (which would be tiresome) 

Current investigation path is exporting to ARM template and populating pipelines from there
